services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\TrainInstitutionBundle\Controller\:
    resource: '../../Controller/'
  Tourze\TrainInstitutionBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  Tourze\TrainInstitutionBundle\Functions\:
    resource: '../../Functions/'
  Tourze\TrainInstitutionBundle\Procedure\:
    resource: '../../Procedure/'
  Tourze\TrainInstitutionBundle\Service\:
    resource: '../../Service/'
  Tourze\TrainInstitutionBundle\Value\:
    resource: '../../Value/'

  symfony-ecol.property-accessor:
    class: Symfony\Component\PropertyAccess\PropertyAccessor
    factory: [ 'Symfony\Component\PropertyAccess\PropertyAccess', 'createPropertyAccessor' ]
